apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: baz 
  janus-idp.io/tekton: baz
  backstage.io/kubernetes-id: baz
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: baz
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml